# Generated by Django 5.1 on 2024-09-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_listings_watchlist_listings_watched_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listings_watched',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing_watching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_watching', to='auctions.listing'),
        ),
    ]
