# Generated by Django 5.1 on 2024-09-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_bid_listing_bids_bid_user_bids_highest_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='last_bid',
            new_name='latest_bid',
        ),
    ]
