# Generated by Django 5.1 on 2024-09-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_highest_bid_bids_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='latest_bid',
            new_name='bid_time',
        ),
    ]
