# Generated by Django 5.1 on 2024-09-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_latest_bid_bids_bid_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing_comments',
        ),
    ]
