# Generated by Django 5.1 on 2024-09-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bids_bid_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_counter',
            field=models.IntegerField(default=0),
        ),
    ]
